#!/usr/bin/env bash
# Redisplays the QR code / setup key for an already-generated TOTP seed —
# for onboarding another teammate, or if someone needs to re-scan it.
# Never regenerates the secret (that would invalidate every phone already
# set up with the old one); just re-renders the same one.

set -euo pipefail

SECRET_FILE="${1:-secrets/totp_secret}"

if [[ ! -f "$SECRET_FILE" ]]; then
	echo "show-totp-qr.sh: $SECRET_FILE not found — pass the path to a totp_secret file" >&2
	echo "                 (generated by scripts/generate-keys.sh)" >&2
	exit 1
fi

TOTP_SECRET="$(cat "$SECRET_FILE")"
OTPAUTH_URI="otpauth://totp/Warden?secret=${TOTP_SECRET}&issuer=Warden&digits=6&period=30"

echo "==> Scan this in an authenticator app (Google Authenticator, Authy, 1Password, ...)"
if command -v qrencode >/dev/null 2>&1; then
	qrencode -t ANSIUTF8 "$OTPAUTH_URI"
else
	echo "    (install 'qrencode' to render this as a scannable QR code here instead of typing it in)"
fi
echo "    Or add it manually — most apps have an 'enter setup key' option:"
echo "      secret: $TOTP_SECRET"
